### ISSUE TITLE
VL result should allow the user to select TMD or other where the user enters the VL result.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/opensrp-client-ecap-chw#373] opened 2021-11-30 12:47 UTC
If the user enters a VL result that is below 1000 copies , the next question should be ticked No and if the user enters a VL result that is more than 1000 copies. The next field should indicate yes.

**Comment by tobiasmakai** [comment] 2021-12-14 00:29
On the form named "Enrolment into OVC Program, if in the field labelled "Last VL results", any number less than 1000 is entered, the option "No" under the next field labeled "Is the child VL suppressed?" should automatically be selected  and "Yes" cannot be selected unless the previous field is filled-in with 1000 or above.

**Comment by chobela** [comment] 2022-01-24 04:58
This is a duplicate of Issue #296

**Closed** 2022-03-07 09:26 UTC
Labels: Client's Feedback
